apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acs-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hamzarhaiem/acs-splunk.git
    targetRevision: main
    path: security/acs/operator
  destination:
    server: https://kubernetes.default.svc
    namespace: rhacs-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
