apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acs-central
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hamzarhaiem/acs-splunk.git
    targetRevision: main
    path: security/acs/central
  destination:
    server: https://kubernetes.default.svc
    namespace: stackrox
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
