apiVersion: platform.stackrox.io/v1alpha1
kind: SecuredCluster
metadata:
  name: secured-cluster
  namespace: stackrox
spec:
  clusterName: local-cluster
  centralEndpoint: central.stackrox.svc:443
  sensor:
    tls: {}
  collector:
    collection: EBPF
