apiVersion: platform.stackrox.io/v1alpha1
kind: Central
metadata:
  name: central
  namespace: stackrox
spec:
  central:
    exposure:
      nodePort:
        port: 443
      type: NodePort
  scanner:
    scalable: false

